tonsbergtur/rebus/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views import LocationListView, LocationDetailView, GeoProblemView, KnowledgeTextProblemView, KnowledgeNumberProblemView, OpenProblemView, TeamNameView, ResultView

app_name = 'rebus'
urlpatterns = [
    path('location/', LocationListView.as_view(), name='location-list'),
    path('location/<int:pk>/', LocationDetailView.as_view(), name='location-detail'),
    path('check-location/', GeoProblemView.as_view(), name='check-location'),
    path('check-text/', KnowledgeTextProblemView.as_view(), name='check-text'),
    path('check-number/', KnowledgeNumberProblemView.as_view(), name='check-number'),
    path('check-open/', OpenProblemView.as_view(), name='check-open'),
    path('set-team-name/', TeamNameView.as_view(), name='set-team-name'),
    path('results/', ResultView.as_view(), name='results'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

tonsbergtur/tonsbergtur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(
        template_name='index.html'
        ), 
        name='login'
    ),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('', include('rebus.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tonsbergtur/rebus/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from geopy.distance import distance as geo_distance
from Levenshtein import distance as levenshtein_distance

class Location(models.Model):
    title = models.CharField(
            max_length = 50,
        )
    hidden_title = models.CharField(
            max_length = 50
        )
    description = RichTextUploadingField()

    def __str__(self):
        return self.title

    def get_problem_count(self) -> int:
        return self.geoproblem_set.count() + \
            self.knowledgetextproblem_set.count() + \
            self.knowledgenumberproblem_set.count() + \
            self.openproblem_set.count()

    def get_completed_problem_count(self, user: User) -> int:
        return \
            GeoResponse.objects.values("problem")\
            .filter(problem__location = self, user=user, correct = True)\
            .distinct().count()\
          + KnowledgeTextResponse.objects.values("problem")\
            .filter(problem__location = self, user=user, correct = True)\
            .distinct().count()\
          + KnowledgeNumberResponse.objects.values("problem")\
            .filter(problem__location = self, user=user, correct = True)\
            .distinct().count()\
          + OpenResponse.objects.values("problem")\
            .filter(problem__location = self, user=user, correct = True)\
            .distinct().count()

    def location_completed(self, user: User) -> bool:
        return (self.get_problem_count() == self.get_completed_problem_count(user))

    def location_found(self, user: User) -> bool:
        if self.geoproblem_set.exists():
            if not GeoResponse.objects.filter(problem__location = self, user = user, correct = True).exists():
                return self.title
        return self.hidden_title


class Problem(models.Model):
    class Meta:
        abstract = True

    title = models.CharField(
            max_length=50,
        )
    description = RichTextUploadingField()
    location = models.ForeignKey(Location, on_delete = models.CASCADE)

    def user_has_correct_answer(self, user: User) -> bool:
        raise NotImplementedError
    
    def verify_answer(self) -> bool:
        raise NotImplementedError

    def __str__(self):
        return self.title

class Response(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    correct = models.BooleanField(default = False)

class GeoProblem(Problem):
    latitude = models.FloatField()
    longitude = models.FloatField()
    threshold = models.IntegerField(default=25, help_text='Accepted distance in meters from point')

    def user_has_correct_answer(self, user: User) -> bool:
        return GeoResponse.objects.filter(problem = self, user = user, correct = True).exists()

    def verify_answer(self, submitted_latitude: float, submitted_longitude: float) -> bool:
        d = geo_distance((self.latitude, self.longitude), (submitted_latitude, submitted_longitude)).m
        return d <= self.threshold

class GeoResponse(Response):
    problem = models.ForeignKey(GeoProblem, on_delete = models.CASCADE)
    latitude = models.FloatField()
    longitude = models.FloatField()

class KnowledgeTextProblem(Problem):
    correct_answer = models.CharField(max_length = 100)
    threshold = models.IntegerField(default=0, help_text='Accepted Levenshtein distance between given and correct answer. 0 for only exact answers')
    
    def get_accepted_answer(self, user):
        if self.user_has_correct_answer(user):
            return KnowledgeTextResponse.objects.filter(problem = self, user = user, correct = True).last().answer

    def user_has_correct_answer(self, user: User) -> bool:
        return KnowledgeTextResponse.objects.filter(problem = self, user = user, correct = True).exists()

    def verify_answer(self, submitted_answer: str) -> bool:
        d = levenshtein_distance(self.correct_answer.lower(), submitted_answer.lower())
        return (d <= self.threshold)

class KnowledgeTextResponse(Response):
    problem = models.ForeignKey(KnowledgeTextProblem, on_delete = models.CASCADE)
    answer = models.CharField(max_length = 100)

class KnowledgeNumberProblem(Problem):
    correct_answer = models.FloatField()
    threshold = models.IntegerField(default=0, help_text='Accepted distance from correct answer, in percent. If correct_answer is 0, the distance is treated as if it was 1')
       
    def get_accepted_answer(self, user):
        if self.user_has_correct_answer(user):
            return KnowledgeNumberResponse.objects.filter(problem = self, user = user, correct = True).last().answer

    def user_has_correct_answer(self, user: User) -> bool:
        return KnowledgeNumberResponse.objects.filter(problem = self, user = user, correct = True).exists()

    def verify_answer(self, submitted_answer: float) -> bool:
        if self.correct_answer == 0:
            ratio = 1
        else:
            ratio = self.correct_answer
        d = 100*abs(submitted_answer - self.correct_answer)/ratio
        return (d <= self.threshold)
    
class KnowledgeNumberResponse(Response):
    problem = models.ForeignKey(KnowledgeNumberProblem, on_delete = models.CASCADE)
    answer = models.CharField(max_length = 100)

class OpenProblem(Problem):

    def user_has_correct_answer(self, user: User) -> bool:
        return OpenResponse.objects.filter(problem = self, user = user, correct = True).exists()

    def verify_answer(self):
        return True

class OpenResponse(Response):
    problem = models.ForeignKey(OpenProblem, on_delete = models.CASCADE)

class ExtendedUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    team_name = models.CharField(max_length = 100)
    player = models.BooleanField(blank = True, default = True)

tonsbergtur/rebus/forms.py
from django import forms
from .models import Problem, Response, GeoProblem, GeoResponse, KnowledgeTextProblem, KnowledgeTextResponse, KnowledgeNumberProblem, KnowledgeNumberResponse, OpenProblem, OpenResponse

class ProblemForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ProblemForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Response
        exclude = ['user', 'problem', 'correct']

    def save(self, commit=True, *args, **kwargs):
        m = super(ProblemForm, self).save(commit=False, *args, **kwargs)
        m.user = self.user
        if commit:
            m.save()
        return m

class GeoProblemForm(ProblemForm):
    class Meta(ProblemForm.Meta):
        model = GeoResponse
        widgets = {
                'longitude': forms.HiddenInput(),
                'latitude': forms.HiddenInput()
            }

    def save(self, commit=True, *args, **kwargs):
        m = super(GeoProblemForm, self).save(commit=False, *args, **kwargs)
        m.correct = m.problem.verify_answer(m.latitude, m.longitude)
        if commit:
            m.save()
        return m

class KnowledgeTextProblemForm(ProblemForm):
    class Meta(ProblemForm.Meta):
        model = KnowledgeTextResponse

    def save(self, commit=True, *args, **kwargs):
        m = super(GeoProblemForm, self).save(commit=False, *args, **kwargs)
        m.correct = m.problem.verify_answer(m.answer)
        if commit:
            m.save()
        return m

class KnowledgeNumberProblemForm(ProblemForm):
    class Meta(ProblemForm.Meta):
        model = KnowledgeNumberResponse

    def save(self, commit=True, *args, **kwargs):
        m = super(GeoProblemForm, self).save(commit=False, *args, **kwargs)
        m.correct = m.problem.verify_answer(m.answer)
        if commit:
            m.save()
        return m

class OpenProblemForm(ProblemForm):
    class Meta(ProblemForm.Meta):
        model = OpenResponse

    def save(self, commit=True, *args, **kwargs):
        m = super(GeoProblemForm, self).save(commit=False, *args, **kwargs)
        m.correct = m.problem.verify_answer()
        if commit:
            m.save()
        return m

tonsbergtur/rebus/views.py
from django.http import HttpResponse
from django.views.generic import DetailView, ListView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Value, ExpressionWrapper
from django.db import models

from .models import Location, ExtendedUser, GeoProblem, KnowledgeTextProblem, KnowledgeNumberProblem, OpenProblem, GeoResponse, KnowledgeTextResponse, KnowledgeNumberResponse, OpenResponse
from .serializers import GeoResponseSerializer, KnowledgeTextResponseSerializer, KnowledgeNumberResponseSerializer, OpenResponseSerializer, TeamNameSerializer

from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

class LocationListView(LoginRequiredMixin, ListView):
    model = Location

class LocationDetailView(LoginRequiredMixin, DetailView):
    model = Location

class GeoProblemView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    
    def post(self, request, format=None):
        serializer = GeoResponseSerializer(data = request.data, context = {'user': request.user}, partial=True)
        serializer.is_valid(raise_exception=True)
        m = serializer.save()
        return Response({'status': m.correct}, status=status.HTTP_201_CREATED)

class KnowledgeTextProblemView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):
        serializer = KnowledgeTextResponseSerializer(data = request.data, context = {'user': request.user}, partial=True)
        serializer.is_valid(raise_exception=True)
        m = serializer.save()
        return Response({'status': m.correct}, status=status.HTTP_201_CREATED)

class KnowledgeNumberProblemView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):
        serializer = KnowledgeNumberResponseSerializer(data = request.data, context = {'user': request.user}, partial=True)
        serializer.is_valid(raise_exception=True)
        m = serializer.save()
        return Response({'status': m.correct}, status=status.HTTP_201_CREATED)

class OpenProblemView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):
        serializer = OpenResponseSerializer(data = request.data, context = {'user': request.user}, partial=True)
        serializer.is_valid(raise_exception=True)
        m = serializer.save()
        return Response({'status': m.correct}, status=status.HTTP_201_CREATED)

class TeamNameView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):
        user = request.user
        serializer = TeamNameSerializer(user.extendeduser, data = request.data, context = {'user': request.user}, partial=True)
        serializer.is_valid(raise_exception=True)
        m = serializer.save()
        return Response({'status': 'ok'}, status=status.HTTP_201_CREATED)

class ResultView(TemplateView):
    model = ExtendedUser
    template_name = 'rebus/results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        geoproblems =    GeoProblem.objects.values('id', 'title', 'location', 'location__title').annotate(type=ExpressionWrapper(Value('1geo'), output_field=models.CharField(max_length=20)))
        textproblems =   KnowledgeTextProblem.objects.values('id', 'title', 'location', 'location__title').annotate(type=ExpressionWrapper(Value('2text'), output_field=models.CharField(max_length=20)))
        numberproblems = KnowledgeNumberProblem.objects.values('id', 'title', 'location', 'location__title').annotate(type=ExpressionWrapper(Value('3number'), output_field=models.CharField(max_length=20)))
        openproblems =   OpenProblem.objects.values('id', 'title', 'location', 'location__title').annotate(type=ExpressionWrapper(Value('4open'), output_field=models.CharField(max_length=20)))

        problems = geoproblems.union(textproblems).union(numberproblems).union(openproblems).order_by('location', 'type')

        georesponses =    GeoResponse.objects.values('user_id', 'problem_id').filter(correct=True).annotate(type=ExpressionWrapper(Value('1geo'), output_field=models.CharField(max_length=20))).distinct()
        textresponses =   KnowledgeTextResponse.objects.values('user_id', 'problem_id').filter(correct=True).annotate(type=ExpressionWrapper(Value('2text'), output_field=models.CharField(max_length=20))).distinct()
        numberresponses = KnowledgeNumberResponse.objects.values('user_id', 'problem_id').filter(correct=True).annotate(type=ExpressionWrapper(Value('3number'), output_field=models.CharField(max_length=20))).distinct()
        openresponses =   OpenResponse.objects.values('user_id', 'problem_id').filter(correct=True).annotate(type=ExpressionWrapper(Value('4open'), output_field=models.CharField(max_length=20))).distinct()

        responses = georesponses.union(textresponses).union(numberresponses).union(openresponses)
        responses = list(responses)

        users = ExtendedUser.objects.filter(player=True)

        results = []
        total = [0 for i in users]

        for problem in problems:
            result = [problem['location__title'], problem['title']] + [5*({'user_id': user.id, 'problem_id': problem['id'], 'type': problem['type']} in responses) for user in users]
            for i in range(len(users)):
                total[i] = total[i] + result[i+2]
            results.append(result)

        context['results'] = results
        context['users'] = users
        context['total'] = total

        return context

tonsbergtur/rebus/templates/rebus/location_detail.html
{% extends "base_generic.html" %}

{% load rebus_extras %}

{% block title %}{% location_title location user %} &ndash; {{ user.extendeduser.team_name }}{% endblock %}

{% block back %}<a href="{% url 'rebus:location-list' %}" class="back">&lsaquo;</a>{% endblock %}

{% block content %}
<div class="content">

    <h2>{% location_title location user %}</h2>
    {{ location.description|safe }}

    {% for problem in location.geoproblem_set.all %}
    {% responded_correctly problem user as responded_correctly_flag %}
    <details id="geodetails{{problem.pk}}" {% if responded_correctly_flag %}class="correct" {% endif %}>
        <summary><h3>{{ problem.title }}</h3></summary>
        <div>
            {{ problem.description|safe }}
            {% if not responded_correctly_flag %}
            <div class="form">
                <button class="submit find-me" onclick="geoProblemSubmit({{problem.pk}})">Vi er her</button>
            </div>
            {% endif %}
            <p id="lblgeo{{problem.pk}}"></p>
        </div>
    </details>
    {% endfor %}
    {% for problem in location.knowledgetextproblem_set.all %}
    {% responded_correctly problem user as responded_correctly_flag %}
    <details id="textdetails{{problem.pk}}" {% if responded_correctly_flag %}class="correct" {% endif %}>
        <summary><h3>{{ problem.title }}</h3></summary>
        <div>
            {{ problem.description|safe }}
            {% if not responded_correctly_flag %}
            <div class="form">
                <input type="text" id="text{{problem.pk}}" name="text{{problem.pk}}">
                <button class="submit textproblem" onclick="textProblemSubmit({{problem.pk}})">Send inn svar</button>
            </div>
            {% else %}
            <p class="given_answer">Dere svarte {% get_accepted_answer problem user %}</p>
            {% endif %}
            <p id="lbltext{{problem.pk}}"></p>
        </div>
    </details>
    {% endfor %}
    {% for problem in location.knowledgenumberproblem_set.all %}
    {% responded_correctly problem user as responded_correctly_flag %}
    <details id="numberdetails{{problem.pk}}" {% if responded_correctly_flag %}class="correct" {% endif %}>
        <summary><h3>{{ problem.title }}</h3></summary>
        <div>
            {{ problem.description|safe }}
            {% if not responded_correctly_flag %}
            <div class="form">
                <input type="number" id="number{{problem.pk}}" name="number{{problem.pk}}">
                <button class="submit numberproblem" onclick="numberProblemSubmit({{problem.pk}})">Send inn svar</button>
            </div>
            {% else %}
            <p class="given_answer">Dere svarte: {% get_accepted_answer problem user %}</p>
            {% endif %}
            <p id="lblnumber{{problem.pk}}"></p>
        </div>
    </details>
    {% endfor %}
    {% for problem in location.openproblem_set.all %}
    {% responded_correctly problem user as responded_correctly_flag %}
    <details id="opendetails{{problem.pk}}" {% if responded_correctly_flag %}class="correct" {% endif %}>
        <summary><h3>{{ problem.title }}</h3></summary>
        <div>
            {{ problem.description|safe }}
            {% if not responded_correctly_flag %}
            <div class="form">
                <button class="submit openproblem" onclick="openProblemSubmit({{problem.pk}})">Registrer utført</button>
            </div>
            {% endif %}
            <p id="lblopen{{problem.pk}}"></p>
        </div>
    </details>
    {% endfor %}
</div>
{% endblock %}

tonsbergtur/rebus/templates/rebus/location_list.html
{% extends "base_generic.html" %}

{% load rebus_extras %}

{% block title %}Oppgaver &ndash; {{ user.extendeduser.team_name }}{% endblock %}

{% block back %}<a href="{% url 'index' %}" class="back">&lsaquo;</a>{% endblock %}

{% block content %}
<div class="content">
    <h2>Oppgaver</h2>
    {% if location_list %}
    {% for location in location_list %}
    {% location_completed location user as location_completed_flag %}
    <details class="location{% if location_completed_flag %} correct{% endif %}" {% if location_completed_flag is False %}open{% endif %}>
        <summary>
            <h3>{% location_title location user %}</h3>
        </summary>
        <div>
            <p class="problemcount">Dere har gjort {% problems_completed location user %} av {{ location.get_problem_count }} oppgaver.</p>
            <a class="gavidere" href="{% url 'rebus:location-detail' location.pk %}">Se oppgavene</a>
        </div>
    </details>
    {% endfor %}
    <p>{{ location_list|length }} steder å besøke.</p>

    {% endif %}
</div>
{% endblock %}

tonsbergtur/rebus/templates/rebus/response.html
<form action="/submit/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

tonsbergtur/rebus/templates/rebus/results.html
{% extends "base_generic.html" %}

{% load rebus_extras %}

{% block title %}Resultatliste{% endblock %}

{% block back %}<a href="{% url 'index' %}" class="back">&lsaquo;</a>{% endblock %}

{% block content %}
<div class="content">
    <table>
        <tr><th>Sted</th><th>Oppgave</th>
        {% for user in users %}
            <th>{{user.team_name}}</th>
        {% endfor %}
        </tr>
        {% for result in results %}
            <tr>
                {% for field in result %}
                <td>{{field}}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        <tr>
            <td>Totalt</td>
            <td></td>

            {% for sum in total %}
            <td>{{sum}}</td>
            {% endfor %}
        </tr>
    </table>
</div>
{% endblock %}